version: "3.5"
services:
  db:
    container_name: "db"
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5438:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
    
